import { GRANTS, getDeadlineStatus, type Grant } from "@/data/grants";

export interface AssistantUser {
  name: string;
  province?: string;
  discipline?: string;
  career?: string;
}

function provinceKeywords(province?: string): string[] {
  if (!province) return [];
  const map: Record<string, string[]> = {
    Ontario: ["Ontario", "Toronto", "Mississauga"],
    Alberta: ["Alberta"],
    "British Columbia": ["BC"],
    Manitoba: ["Manitoba"],
    Saskatchewan: ["Saskatchewan"],
    Quebec: ["Quebec"],
  };
  return map[province] ?? [province];
}

function scoreGrant(grant: Grant, user: AssistantUser, query: string): number {
  let score = 0;
  const q = query.toLowerCase();
  const provKeys = provinceKeywords(user.province);

  if (user.discipline && grant.discipline.includes(user.discipline)) score += 4;
  if (provKeys.some((k) => grant.tags.some((t) => t.toLowerCase().includes(k.toLowerCase())))) score += 3;
  if (user.career?.toLowerCase().includes("emerging") && grant.tags.includes("Emerging")) score += 2;
  if (q.includes("diaspora") && grant.tags.includes("Diaspora")) score += 3;
  if (q.includes("bipoc") && grant.tags.includes("BIPOC")) score += 3;
  if (q.includes("indigenous") && grant.tags.some((t) => /indigenous|first nations|inuit|métis/i.test(t))) score += 3;
  if (q.includes("documentary") && grant.discipline.includes("Documentary")) score += 3;
  if (q.includes("film") && grant.discipline.includes("Film")) score += 2;
  if (q.includes("toronto") && grant.tags.includes("Toronto")) score += 3;

  const dl = getDeadlineStatus(grant.close);
  if (dl.days > 0 && dl.days <= 45) score += 1;

  return score;
}

function formatGrantLine(g: Grant): string {
  const dl = getDeadlineStatus(g.close);
  return `• **${g.name}** (${g.org}) — ${g.amount} · ${dl.label}`;
}

function findGrantByName(text: string): Grant | undefined {
  const lower = text.toLowerCase();
  return GRANTS.find(
    (g) => lower.includes(g.name.toLowerCase()) || lower.includes(g.org.toLowerCase().slice(0, 12))
  );
}

function urgentDeadlines(): Grant[] {
  return GRANTS.filter((g) => {
    const dl = getDeadlineStatus(g.close);
    return dl.days > 0 && dl.days <= 45;
  })
    .sort((a, b) => getDeadlineStatus(a.close).days - getDeadlineStatus(b.close).days)
    .slice(0, 8);
}

function recommendGrants(user: AssistantUser, query: string, limit = 6): Grant[] {
  return [...GRANTS]
    .map((g) => ({ g, score: scoreGrant(g, user, query) }))
    .filter(({ score }) => score > 0)
    .sort((a, b) => b.score - a.score)
    .slice(0, limit)
    .map(({ g }) => g);
}

function draftProposal(grant: Grant, user: AssistantUser, query: string): string {
  const projectHint = query.match(/project is[:\s]+(.+)/i)?.[1]?.trim() || "[describe your project]";
  return `**Project summary — ${grant.name}** (${grant.org})

**Applicant:** ${user.name}${user.province ? ` · ${user.province}` : ""}${user.discipline ? ` · ${user.discipline}` : ""}

**Project overview**
${projectHint}

**Artistic rationale**
This work advances my practice by [specific creative goal]. It aligns with ${grant.org}'s mandate: ${grant.description}

**Community impact**
[Who benefits from this work and how — audiences, collaborators, underrepresented communities.]

**Budget & timeline**
Requested support: ${grant.amount}
Key milestones: [pre-production / creation / presentation dates]

**Eligibility fit**
${grant.eligibility}

---
*Draft generated by CanGrants — edit before submitting. Verify current guidelines at the funder's website.*`;
}

function draftArtistStatement(user: AssistantUser, query: string): string {
  const grant = findGrantByName(query);
  const funder = grant?.org ?? "this grant program";
  return `**Artist statement** — ${user.name}

As a ${user.discipline?.toLowerCase() || "Canadian"} artist${user.province ? ` based in ${user.province}` : ""}, my work explores [your themes — identity, diaspora, community, form]. ${user.career ? `At the ${user.career.toLowerCase()} stage of my career, ` : ""}I am developing projects that [one sentence on current focus].

My practice is rooted in [medium/approach] and informed by [communities, collaborators, or research]. Recent work includes [1–2 concrete examples].

This application to ${funder} supports [specific outcome — production, development, presentation]. I am committed to [accessibility, mentorship, equity, or audience engagement — pick what fits your work].

---
*Template from CanGrants — personalize every section before submission.*`;
}

export async function getAssistantReply(
  messages: { role: string; content: string }[],
  user: AssistantUser
): Promise<string> {
  await new Promise((r) => setTimeout(r, 400 + Math.random() * 600));

  const last = messages[messages.length - 1]?.content ?? "";
  const q = last.toLowerCase();

  if (/deadline|urgent|due soon|closing/.test(q)) {
    const urgent = urgentDeadlines();
    if (!urgent.length) {
      return "No fixed deadlines in the next 45 days in our catalog. Check **Rolling** programs in Discover, or widen your search.";
    }
    return `**Upcoming deadlines** (next 45 days):\n\n${urgent.map(formatGrantLine).join("\n")}\n\nOpen **Discover** and filter by **Urgent** for the full list.`;
  }

  if (/draft|proposal|project summary|write.*(for|application)/.test(q)) {
    const grant = findGrantByName(last) ?? recommendGrants(user, last, 1)[0];
    if (!grant) {
      return "Name the grant in your message (e.g. “MAC Matchmaker” or “Talent to Watch”) and describe your project — I’ll draft a starter summary.";
    }
    return draftProposal(grant, user, last);
  }

  if (/artist statement|statement for/.test(q)) {
    return draftArtistStatement(user, last);
  }

  if (/eligible|eligibility|which grant|recommend|fit for|right grant/.test(q)) {
    const matches = recommendGrants(user, last, 8);
    if (!matches.length) {
      return `I couldn’t match grants to your profile yet. Try adding your **discipline** and **province** in your account, or mention keywords like *film*, *Toronto*, *emerging*, or *diaspora*.\n\nYou can still browse all **${GRANTS.length}** grants in Discover.`;
    }
    return `**Grants that may fit ${user.name.split(" ")[0]}**${user.discipline ? ` (${user.discipline}` : ""}${user.province ? `${user.discipline ? ", " : " ("}${user.province}` : ""}${user.discipline || user.province ? ")" : ""}:\n\n${matches.map(formatGrantLine).join("\n")}\n\nTap **Details** on any card for full eligibility. I can also **draft a proposal** — tell me the grant name and your project.`;
  }

  if (/how many|what is cangrants|help|hello|hi\b/.test(q)) {
    return `CanGrants tracks **${GRANTS.length}** Canadian and international arts funding opportunities.\n\nI can:\n• Recommend grants for your profile\n• List **urgent deadlines**\n• **Draft** proposals or artist statements\n\nTry: “Which grants am I eligible for?” or “What are the most urgent deadlines?”`;
  }

  const fallback = recommendGrants(user, last, 5);
  if (fallback.length) {
    return `Here are some grants related to your question:\n\n${fallback.map(formatGrantLine).join("\n")}\n\nAsk about **eligibility**, **deadlines**, or say **draft a proposal for [grant name]**.`;
  }

  return `I’m your CanGrants assistant. Ask about **eligibility**, **upcoming deadlines**, or request a **draft proposal** for a specific grant. Browse all programs in the **Discover** tab.`;
}
